export const SET_USER = 'SET_USER';

export const SET_ACCOUNT = 'GET_ACCOUNT';

export const DELETE_AUTO_PAYMENT = 'DELETE_AUTO_PAYMENT';
export const SET_AUTO_PAYMENT = 'SET_AUTO_PAYMENT';
export const CREATE_AUTO_PAYMENT = 'CREATE_AUTO_PAYMENT';

export const CREATE_PAYMENT = 'CREATE_PAYMENT';

export const TRANSFER_PAYMENT = 'TRANSFER_PAYMENT';

export const TRANSFER_CREATED = 'TRANSFER_CREATED';
export const TRANSFER_PANEL = 'TRANSFER_PANEL';

export const PAYMENT_CREATED = 'PAYMENT_CREATED';
export const PAYMENT_PANEL = 'PAYMENT_PANEL';

export const SET_TRANSACTION = 'SET_TRANSACTION';
